### ISSUE TITLE
How to consume zoom windows csharp wrapper in c# application

### ISSUE THREAD

**Issue by jigipatel** [zoom/zoom-c-sharp-wrapper#2]
Hello,

i'm getting trouble in finding function in wrapper dll which i want to call if you have any document than please provide me.

how do i call login and start meeting function of dll ?

Thank you so much for this windows zoom wrapper dll.

**Comment by datsliao** [comment]
login:
` //add callback event
            ZOOM_SDK_DOTNET_WRAP.CZoomSDKeDotNetWrap.Instance.GetAuthServiceWrap().Add_CB_onLoginRet(onLoginRet);
            ZOOM_SDK_DOTNET_WRAP.CZoomSDKeDotNetWrap.Instance.GetAuthServiceWrap().Add_CB_onLogout(onLogout);

            //login
            ZOOM_SDK_DOTNET_WRAP.LoginParam param = new ZOOM_SDK_DOTNET_WRAP.LoginParam();
            param.loginType = ZOOM_SDK_DOTNET_WRAP.LoginType.LoginType_Email;
            ZOOM_SDK_DOTNET_WRAP.LoginParam4Email email_info = new ZOOM_SDK_DOTNET_WRAP.LoginParam4Email();
            email_info.userName = "xx@xx.xx";
            email_info.password = "psw";
            email_info.bRememberMe = [true or false];
            param.emailLogin = email_info;

            ZOOM_SDK_DOTNET_WRAP.CZoomSDKeDotNetWrap.Instance.GetAuthServiceWrap().Login(param)`

**Comment by jigipatel** [comment]
Heartily thank you datsliao,
can you please help me with more function calling
how to start chat ?
how to add contact and create group ?
how to get contact list ?

**Comment by datsliao** [comment]
sorry. windows sdk don't support IM feature.

**Comment by jigipatel** [comment]
but sir windows zoom app has all this features

**Comment by jigipatel** [comment]
Hello sir,
 in case of start meeting with API User Type (SDKUserType.SDK_UT_APIUSER)
 i'm getting below error   

![api user mitting start call](https://user-images.githubusercontent.com/33049650/32441586-4b46e054-c31e-11e7-98d6-bb32c37eaf15.png)

Thank You.

**Comment by datsliao** [comment]
zoom windows sdk we don't support IM now. sorry for that.
for start meeting issue, if you use login user,  please start meeting for login user
ZOOM_SDK_DOTNET_WRAP.StartParam param = new ZOOM_SDK_DOTNET_WRAP.StartParam();
param.userType = ZOOM_SDK_DOTNET_WRAP.SDKUserType.SDK_UT_NORMALUSER;
ZOOM_SDK_DOTNET_WRAP.StartParam4NormalUser start_login_user_param = new ZOOM_SDK_DOTNET_WRAP.StartParam4NormalUser();
start_login_user_param.meetingNumber = xxx;
param.normaluserStart = start_login_user_param;
ZOOM_SDK_DOTNET_WRAP.SDKError err = ZOOM_SDK_DOTNET_WRAP.CZoomSDKeDotNetWrap.Instance.GetMeetingServiceWrap().Start(param);

the start meeting in our demo, it is for api user. 
thanks.

**Comment by jigipatel** [comment]
Hello Sir,
I implemented start meeting using normal user (SDK_UT_NORMALUSER) now 

"my requirement is to start meeting using API user (SDK_UT_APIUSER)" and where i'm getting response "ZOOM_SDK_DOTNET_WRAP.SDKError.SDKERR_WRONG_USEAGE"

![api user mitting start call1](https://user-images.githubusercontent.com/33049650/32482185-8e252f22-c3bc-11e7-9fc7-e8573ee27947.png)

**Comment by datsliao** [comment]
now you pass the SDK_UT_APIUER, This is for API user, not for login user.
if you want to use login user to start meeting, please use the follow code.
ZOOM_SDK_DOTNET_WRAP.StartParam param = new ZOOM_SDK_DOTNET_WRAP.StartParam();
param.userType = ZOOM_SDK_DOTNET_WRAP.SDKUserType.# SDK_UT_NORMALUSER;
ZOOM_SDK_DOTNET_WRAP.# StartParam4NormalUser start_login_user_param = new ZOOM_SDK_DOTNET_WRAP.StartParam4NormalUser();
start_login_user_param.meetingNumber = xxx;
param.normaluserStart = start_login_user_param;
ZOOM_SDK_DOTNET_WRAP.SDKError err = ZOOM_SDK_DOTNET_WRAP.CZoomSDKeDotNetWrap.Instance.GetMeetingServiceWrap().Start(param);

**Comment by jigipatel** [comment]
Thank You Sir,
can you please tell me what is the API user and what is normal login user i'm so confused yet.

**Comment by datsliao** [comment]
API user is created via REST API. we need to use the user id and user token to start meeting 
Normal user is registered via email. we need to login with the email and psw firstly, and after that, we can start/join meeting with meeting number.
thanks.

**Comment by jigipatel** [comment]
Hello Sir,
Got it. Thank You so much for clear my confusion. i want one more help can you please tell me how do i replace or remove "powered by Zoom" logo from video calling screen.
Thank You.

**Comment by WeiGuoZoom** [comment]
Hi, normally Zoom doesn't remove "powered by Zoom" logo, it's in the License file.

**Comment by jigipatel** [comment]
Hello Sir,
How can i change video call UI like screen color and title to another language.
for this changes which file i need to modify ?
Thank You.

**Comment by jigipatel** [comment]
Hello,
video calling screen is coming from web view ?

**Comment by datsliao** [comment]
now we don't support change the screen color of video windows.
about using other language,
1. you need to open the zwinres.dll, and save the language string to xml file
![image](https://user-images.githubusercontent.com/9944213/32637895-61a1feca-c5f7-11e7-861e-7a7070ecdd9c.png)
2.translate the all string to the language you want, 
![image](https://user-images.githubusercontent.com/9944213/32637969-d0d62c30-c5f7-11e7-9048-29d25b688e85.png)

3.pass your language xml file path when you init sdk.
![image](https://user-images.githubusercontent.com/9944213/32638105-7d06706e-c5f8-11e7-9c62-7cad466c60fa.png)

**Comment by jigipatel** [comment]
Hello sir,
Can you please provide me Zoom Windows SDK C# wrapper DLL Build in ".net framework 3.5".

**Comment by datsliao** [comment]
we already public the source code. you can build it by yourself. thanks.:)

**Comment by jigipatel** [comment]
I'm getting few error and i wont able to solve it that's why i ask here.

**Comment by jigipatel** [comment]
Hello again ,
"Invite" option is missing from meeting screen when i start meeting or join meeting using windows zoom sdk wrapper. can you tell me how can i add invite feature into meeting screen.

**Comment by datsliao** [comment]
window sdk don't have "Invite" button.
workaround:
1>IMeetingConfigurationDotNetWrap::EnableInviteButtonOnMeetingUI
and IMeetingUIControllerDotNetWrap::Add_CB_onInviteBtnClicked
after this, will show invite button on meeting ui
2>when click the invite button, you will get the public delegate void onInviteBtnClicked() callback event,
you can show your own invite dialog.
3>these apis are for get the invite information
a>IMeetingServiceDotNetWrap::GetMeetingInfo
b>
IMeetingInfo::GetInviteEmailTeamplate
IMeetingInfo::GetInviteEmailTitle
IMeetingInfo::GetJoinMeetingUrl
thanks
dats

**Comment by jigipatel** [comment]
ZOOM_SDK_DOTNET_WRAP.CMeetingConfigurationDotNetWrap.Instance.EnableInviteButtonOnMeetingUI(true);
ZOOM_SDK_DOTNET_WRAP.CMeetingUIControllerDotNetWrap.Instance.Add_CB_onInviteBtnClicked(onInviteBtnClicked);

 public void onInviteBtnClicked()
        {
            IMeetingInfo meetingInfo = ZOOM_SDK_DOTNET_WRAP.CMeetingServiceDotNetWrap.Instance.GetMeetingInfo();
            String meetingid = meetingInfo.GetMeetingID();

            MessageWindow mw = new MessageWindow(meetingid);
            mw.ShowDialog();
        }

i did some thing like this but i'm not getting callback when i click on invite. am i missing something ?

**Comment by datsliao** [comment]
one bug in c# wrap, we will fix this in next release.
workaround:
change your local code:
macro_define.h
![image](https://user-images.githubusercontent.com/9944213/33354194-a0937fba-d4ec-11e7-9b19-56fe6a030694.png)

**Comment by jigipatel** [comment]
Hello,
i made this changes in .h file now i need to build DLL for wrapper while building DLL i'm getting abow errors so i copy "h" folder from "zoom-sdk-windows-master" and pest inside "Zoom-Windows-Csharp-wrapper-master" folder. my previous error is gone but i'm getting few new errors like 

Error	C2143	syntax error: missing ')' before 'const'      meeting_service_wrap.h	65
Error	C2061	syntax error: identifier 'StatisticsWarningType'      meeting_service_wrap.h	70
Error	C2061	syntax error: identifier 'IMeetingExternalSecureKeyHandler'  meeting_service_wrap.h
Error	C2059	syntax error: 'const'     meeting_service_wrap.h	65
Error	C2059	syntax error: ')'    meeting_service_wrap.h	65
Error	C2947	expecting '>' to terminate template-argument-list, found '>' meeting_service_wrap.h
Error	C2678	binary '=': no operator found which takes a left-hand operand of type 'std::function' (or there is no acceptable conversion)    meeting_service_dotnet_wrap.cpp	243

and so on...

can you please tell me how do i solve this errors and build DLL for c# wrapper 
Thank You so much.

**Comment by datsliao** [comment]
please follow the steps here to build c# wrapper.
https://developer.zoom.us/docs/windows/c-wrapper-introduction/

**Comment by jigipatel** [comment]
Hello ,
i followed above steps still i'm getting same error.
actually i'm using visual studio 2017 and i change target also
![target version issue](https://user-images.githubusercontent.com/33049650/33369414-86e3c7d6-d51a-11e7-87c1-3eb5714e27e1.png)

is there any fix visual studio version i need to use ?

**Comment by jigipatel** [comment]
Hello,
I don't find MeetingService Listener where i come to know meeting MEETING_CONNECTED status.

**Comment by jigipatel** [comment]
Hello, 
How can i remove or hide meeting id from title bar of meeting screen 
![titlebar](https://user-images.githubusercontent.com/33049650/33660243-2fd27ea8-daa9-11e7-912f-4cc70eb0819a.png)

**Comment by datsliao** [comment]
hi，
meeting status callback:
IMeetingServiceDotNetWrap
void Add_CB_onMeetingStatusChanged(onMeetingStatusChanged cb);

api for hide the meeting id:
IMeetingConfigurationDotNetWrap
void HideMeetingInfoFromMeetingUITitle([MarshalAs(UnmanagedType.U1)] bool bHide);

**Comment by jigipatel** [comment]
1. How do i get recorded meetings file path ?

2. i can not able to start meeting without passing personal meeting id using API user so,
how to start meeting with API user without passing personal meeting id?

3. i cant able find MEETING_CONNECTED status and callback.

4. if you have any idea about above error list  than please suggest me because still i'm getting abow 13 error in build wrapper DLL. i also installed visual studio 2015 with update 3 but still i'm getting same error.

Thank you so much for all your response

**Comment by datsliao** [comment]
How do i get recorded meetings file path ?
IMeetingRecordingControllerDotNetWrap
Add_CB_onRecording2MP4Done
once recoding convert done, we will give your this callback event include file path.

i can not able to start meeting without passing personal meeting id using API user so,
how to start meeting with API user without passing personal meeting id?
you also need to pass user token and id, if you use API User to start meeting.
namespace ZOOM_SDK_DOTNET_WRAP
{
	// Token: 0x020004C9 RID: 1225
	public struct StartParam4APIUser
	{
		// Token: 0x04000584 RID: 1412
		public string userID;

		// Token: 0x04000585 RID: 1413
		public string userToken;

		// Token: 0x04000586 RID: 1414
		public string userName;

		// Token: 0x04000587 RID: 1415
		public ulong meetingNumber;

		// Token: 0x04000588 RID: 1416
		public HWNDDotNet hDirectShareAppWnd;

		// Token: 0x04000589 RID: 1417
		public string participantId;

		// Token: 0x0400058A RID: 1418
		public bool isDirectShareDesktop;
	}
}
i cant able find MEETING_CONNECTED status and callback.
IMeetingServiceDotNetWrap
void Add_CB_onMeetingStatusChanged(onMeetingStatusChanged cb);

if you have any idea about above error list than please suggest me because still i'm getting abow 13 error in build wrapper DLL. i also installed visual studio 2015 with update 3 but still i'm getting same error.
please follow the steps on our wiki
https://developer.zoom.us/docs/windows/c-wrapper-introduction/
Download Zoom windows sdk and Unzip.
Download Zoom C# wrap and Unzip.
Copy ‘h’ folder in windows sdk to ‘zoom_sdk_c_sharp_wrap’ folder in C# wrap.
Copy all files of ‘bin’ folder in windows sdk to ‘bin’ folder in C# wrap
Goto the ‘zoom_sdk_c_sharp_wrap’ folder, open the zoom_sdk_c_sharp_wrap.sln via VS2015
Change project setting to build and run (x86 and release)

**Comment by jigipatel** [comment]
Hello,
1. My code for recorded meetings file path access 

ZOOM_SDK_DOTNET_WRAP.CMeetingRecordingControllerDotNetWrap.Instance.Add_CB_onRecording2MP4Done(onRecording2MP4Done);

        public void onRecording2MP4Done(bool bsuccess, int iResult, string szPath)
        {
            if (bsuccess)
            {
                String path = szPath;
            }
        }

i'm not getting CALLBACK.

2. I successfully started meeting with API user but i compulsory need to pass personal meeting id in parameter otherwise i got INVALID_SDK_PARAMETER response but,
My requirement is to create new meeting id every time i start meeting like zoom app.

**Comment by datsliao** [comment]
1. now this version c# wrap had a bug as we talked before. we will fix it in next release. you can fix this issue in your local as follow,
![image](https://user-images.githubusercontent.com/9944213/33987995-d579d8ce-e0fd-11e7-806e-e8ff264362f6.png)

2. you need to use zoom REST API to get different meeting id, and start this meeting via zoom windows sdk.
thanks

**Comment by jigipatel** [comment]
hello, 
Can you please tell me when we get next release?

**Comment by WeiGuoZoom** [comment]
Hi,
1. the next release will be around mid of Jan.
2. Please take a look at Zoom's developer website: https://developer.zoom.us/playground/#/Meetings/meetingCreate

**Comment by jigipatel** [comment]
Hello,
1. How to change or replace invitation URL on audio call screen?

![non video screen](https://user-images.githubusercontent.com/33049650/34069518-28c0929e-e279-11e7-9210-11b27b310110.png)

Thank You.

**Comment by jigipatel** [comment]
Hello,
Can you please provide me windows zoom SDK wrapper dll with below changes 
1. Callback issue  
2. Downgrade .net frame work to version 3

i tried everything  but still getting above  13 error, i wont able to build dll and i don't understand what is the error and how to solve it.

i can't wait for next release i have project deadline 31'st December so, please help me.
please provide me dll (email jignashakotadiya15@gmail.com)

**Comment by datsliao** [comment]
we plan to have a hot fix release end of this week or next week.  we will fix this callback issue. but we can't to downgrade to .net frame 3.0.
before this release, we can provide the local build dlls to u. sorry for that.
thanks.

**Comment by jigipatel** [comment]
Ok , thank you so much.
Can you please answer previous question
1. How to change or replace invitation URL on audio call screen?

**Comment by datsliao** [comment]
now we don't support to change this url. sorry for that.

**Comment by jigipatel** [comment]
can i hide this invitation URL  and CopyLink Button?

**Comment by datsliao** [comment]
1.sorry, don't support this.
2.please wait our hot fix release. i can't provide the local build to u.  sorry for that.

**Comment by jigipatel** [comment]
Hello,
how can i hide video calling screen watermark ?

**Comment by jigipatel** [comment]
Hello Sir,
Because of christmas holyday i got project deadline 23'rd December can you please provide new release as soon as possible ?

**Comment by jigipatel** [comment]
Hello,
I got new release and when i Authenticat SDK i got onLoginRet delegate call and it gives me LOGINSTATUS LOGIN_IDLE( Not login) i wont able to Authenticat SDK.

1. how to Authenticat SDK?
   - i'm using same code and zoom pro account credentials where with same credentials old SDK is 
     working perfectly fine.
   - when i got onLoginRet delegate call my application become at break point 
   - for Authenticat SDK i'm using same code is provided by you.
