### ISSUE TITLE
SDK callback issue

### ISSUE THREAD

**Issue by manthan-oneclick** [zoom/zoom-c-sharp-wrapper#4]
Hello,
i'm still not getting onInviteBtnClicked delegate callback in latest release 
here is my code:
//invite
ZOOM_SDK_DOTNET_WRAP.CMeetingConfigurationDotNetWrap.Instance.EnableInviteButtonOnMeetingUI(true); ZOOM_SDK_DOTNET_WRAP.CMeetingUIControllerDotNetWrap.Instance.Add_CB_onInviteBtnClicked(onInviteBtnClicked);

public void onInviteBtnClicked()
{
IMeetingInfo meetingInfo = ZOOM_SDK_DOTNET_WRAP.CMeetingServiceDotNetWrap.Instance.GetMeetingInfo();
String meetingid = meetingInfo.GetMeetingID();
}

**Comment by datsliao** [comment]
hi, please don't use the CMeetingConfigurationDotNetWrap and CMeetingUIControllerDotNetWrap directly. 

change your code like this, and try again.
ZOOM_SDK_DOTNET_WRAP.CMeetingConfigurationDotNetWrap.Instance.EnableInviteButtonOnMeetingUI(true);            ZOOM_SDK_DOTNET_WRAP.CMeetingUIControllerDotNetWrap.Instance.Add_CB_onInviteBtnClicked(onInviteBtnClicked);
Regards
Dats

**Comment by manthan-oneclick** [comment]
Hello,
Thank You.
1. how to restrict 3'rd user to join meeting ?
